version: "3"

vars:
  GREETING: Hello, Bhojpur Routes Developer!

tasks:
    default:
        cmds:
        - echo "{{.GREETING}}"
        silent: true

    build-tools:
        desc: Build the Intelligent Routing software tools
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/routectl ./client.go 
        - chmod 755 bin/routectl
        - cp bin/routectl $GOPATH/bin
        - GOFLAGS=-mod=mod go build -o bin/routesvr ./server.go 
        - chmod 755 bin/routesvr
        - cp bin/routesvr $GOPATH/bin

    build-desktop:
        desc: Build the desktop application for current OS
        cmds:
        - guiutl package -name "Bhojpur Routes" -os macos -icon routes.png
        - guiutl package -name "Bhojpur Routes" -os linux -icon routes.png
        - guiutl package -name "Bhojpur Routes" -os windows -icon routes.png

    package-android:
        desc: Package the mobile application for Android
        cmds:
        - guiutl package -name "Bhojpur Routes" -os android -appID net.bhojpur.routes -icon routes.png

    package-ios:
        desc: Package the mobile application for iOS
        cmds:
        - guiutl package -name "Bhojpur Routes" -os ios -appID net.bhojpur.routes -icon routes.png

    release-macos:
        desc: Release the native application for macOS App Store
        cmds:
        - guiutl release -appID net.bhojpur.routes -appVersion 1.0 -appBuild 1 -category business

    release-android:
        desc: Release the mobile application for Google Play
        cmds:
        - guiutl release -os android -appID net.bhojpur.routes -appVersion 1.0 -appBuild 1

    release-ios:
        desc: Release the mobile application for iOS App Store
        cmds:
        - guiutl release -os ios -appID net.bhojpur.routes -appVersion 1.0 -appBuild 1

    run-web-server:
        desc: Run the web server application from source code
        cmds:
        - GOFLAGS=-mod=mod go run server.go
 
    run-web-client:
        desc: Run the web client application from source code
        cmds:
        - GOFLAGS=-mod=mod go run client.go

    run-mobile:
        desc: Run the mobile client application on emulator
        cmds:
        - GOFLAGS=-mod=mod go run -tags mobile native/main.go

    run-desktop: 
        desc: Run the desktop application on local host
        cmds:
        - GOFLAGS=-mod=mod go run native/main.go

    generate:
        desc: Generate Go source code from Protocol Buffers
        cmds:
        - protoc --proto_path=. --proto_path=$GOPATH/src/googleapis --proto_path=$GOPATH/src/github.com/gogo/protobuf --go_out=./pkg/api --go_opt=module=github.com/bhojpur/routes/pkg/api pkg/api/v1/vesting/vesting.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/googleapis --proto_path=$GOPATH/src/github.com/gogo/protobuf --go-grpc_out=. --go-grpc_opt=paths=source_relative pkg/api/v1/vesting/vesting.proto

    test:
        desc: Execute all the Unit Tests
        cmds:
        - gotestsum --junitfile test-results/unit-tests.xml -- -short -race -cover -coverprofile test-results/cover.out ./...

    swagger.gen:
        desc: Generate Go source code
        cmds:
        - GOFLAGS=-mod=mod go generate bhojpur.net/routes/internal bhojpur.net/routes/pkg/swagger

    swagger.validate:
        desc: Validate all the Swagger API specifications
        cmds:
        - swagger validate pkg/swagger/swagger.yml

    swagger.doc:
        desc: Generate documentation for Swagger specified APIs
        cmds:
        - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html