// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RoutesUIClient is the client API for RoutesUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoutesUIClient interface {
	// ListEngineSpecs returns a list of Routes Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (RoutesUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type routesUIClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutesUIClient(cc grpc.ClientConnInterface) RoutesUIClient {
	return &routesUIClient{cc}
}

func (c *routesUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (RoutesUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &RoutesUI_ServiceDesc.Streams[0], "/v1.RoutesUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &routesUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoutesUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type routesUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *routesUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routesUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.RoutesUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutesUIServer is the server API for RoutesUI service.
// All implementations must embed UnimplementedRoutesUIServer
// for forward compatibility
type RoutesUIServer interface {
	// ListEngineSpecs returns a list of Routes Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, RoutesUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedRoutesUIServer()
}

// UnimplementedRoutesUIServer must be embedded to have forward compatible implementations.
type UnimplementedRoutesUIServer struct {
}

func (UnimplementedRoutesUIServer) ListEngineSpecs(*ListEngineSpecsRequest, RoutesUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedRoutesUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedRoutesUIServer) mustEmbedUnimplementedRoutesUIServer() {}

// UnsafeRoutesUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutesUIServer will
// result in compilation errors.
type UnsafeRoutesUIServer interface {
	mustEmbedUnimplementedRoutesUIServer()
}

func RegisterRoutesUIServer(s grpc.ServiceRegistrar, srv RoutesUIServer) {
	s.RegisterService(&RoutesUI_ServiceDesc, srv)
}

func _RoutesUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoutesUIServer).ListEngineSpecs(m, &routesUIListEngineSpecsServer{stream})
}

type RoutesUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type routesUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *routesUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _RoutesUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.RoutesUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutesUI_ServiceDesc is the grpc.ServiceDesc for RoutesUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutesUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.RoutesUI",
	HandlerType: (*RoutesUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _RoutesUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _RoutesUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "routes-ui.proto",
}
